# This is an example configuration. Put something like this into `~/.envdo.toml`

[default]
# if no profile is specified, `envdo` will use the default profile
FOO = "yes"
BAR = "certainly"

[alpha]
FOO = "correct"
BAR = "battery"

[beta]
FOO = "horse"
BAR = "okay!"
